version: "3"
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: university

  university-api:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      DATABASE_URL: postgresql://postgres:5432/university
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
    ports:
      - "8080:8080"
    depends_on:
      - postgres